[package]
name = "concatfiles"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
ignore = "0.4"
indicatif = "0.17"
open = "5.0"
glob = "0.3"